all:
    hosts:
        isu7f-1.:
        isu7f-2.:
        isu7f-3.:
        isu7f-4.:
        isu7f-5.:
    vars:
        ansible_python_interpreter:
            /usr/bin/python
        ansible_user:
            root
