- hosts: all
  become: yes

  tasks:
    - include_vars: users.yml
      name: users

    - include:
        create_a_user.yml id={{ item.id }} ssh_key={{ item.ssh_key }}
      with_items: "{{ users }}"

    - name: passwordless su
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel\s'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'

    - name: passwordless su
      lineinfile:
        path: /etc/sudoers
        state: present
        line: '%adm ALL=(ALL) NOPASSWD: ALL'

    - name: パスワード認証の無効化
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        insertafter: "^#PasswordAuthentication"
        line: "PasswordAuthentication no"

    - name: チャレンジ・レスポンス認証の無効化
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^ChallengeResponseAuthentication"
        insertafter: "^#ChallengeResponseAuthentication"
        line: "ChallengeResponseAuthentication no"

    - name: PATH go
      lineinfile:
        path: /home/isucon/.bashrc
        state: present
        line: 'export PATH=~/local/go/bin:$PATH'

    - include:
        packages.yml

    - include:
        selinux.yml

    - include:
        backup.yml

    - include:
        copy.yml

    - include:
        github.yml
