- hosts: all
  become: yes

  tasks:
  - name: clone repository
    shell: git clone git@github.com:y1r/isucon6-yosen.git
    args:
        chdir: ~isucon
        creates: ~isucon/isucon6-yosen
    become: yes
    become_user: isucon
